# my-backstage-entities
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-test-app
  description: An example of a Backstage application.
  # Example for optional annotations
  annotations:
    github.com/project-slug: boojaa-k/my-backstage-entities
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: boojaasri.kalidass@atmecs.com
  lifecycle: experimental
